---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
- name: Ensure apt packages are installed
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  loop: "{{ apt_packages }}"
- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: true
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true