---
- name: Make sure helm repos are installed
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop: "{{ helm_repos }}"
  tags: ['helm']

- name: Make sure the necessary namespaces for helm exist
  kubernetes.core.k8s:
    name: "{{ item.namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  loop: "{{ helm_charts }}"
  tags: ['helm']

- name: Make sure helm charts are installed
  kubernetes.core.helm:
    name: "{{ item.name }}"
    namespace: "{{ item.namespace }}"
    chart_ref: "{{ item.chart_ref }}"
  loop: "{{ helm_charts }}"
  tags: ['helm']